function mostrar (){
    document.getElementById('info').style.display='block'
    document.getElementById('sol1').style.display='block'
    document.getElementById('mercurio2').style.display='none'
    document.getElementById('venus3').style.display='none'
    document.getElementById('tierra4').style.display='none'
    document.getElementById('marte5').style.display='none'
    document.getElementById('jupiter6').style.display='none'
    document.getElementById('saturno7').style.display='none'
    document.getElementById('urano8').style.display='none'
    document.getElementById('neptuno9').style.display='none'
document.getElementById('info2').style.display='none'
document.getElementById('info3').style.display='none'
document.getElementById('info4').style.display='none'
document.getElementById('info5').style.display='none'
document.getElementById('info6').style.display='none'
document.getElementById('info7').style.display='none'
document.getElementById('info8').style.display='none'
document.getElementById('info9').style.display='none'
}

function mostrar2 (){
    document.getElementById('info').style.display='none'
    document.getElementById('sol1').style.display='none'
    document.getElementById('mercurio2').style.display='block'
    document.getElementById('venus3').style.display='none'
    document.getElementById('tierra4').style.display='none'
    document.getElementById('marte5').style.display='none'
    document.getElementById('jupiter6').style.display='none'
    document.getElementById('saturno7').style.display='none'
    document.getElementById('urano8').style.display='none'
    document.getElementById('neptuno9').style.display='none'
document.getElementById('info2').style.display='block'
document.getElementById('info3').style.display='none'
document.getElementById('info4').style.display='none'
document.getElementById('info5').style.display='none'
document.getElementById('info6').style.display='none'
document.getElementById('info7').style.display='none'
document.getElementById('info8').style.display='none'
document.getElementById('info9').style.display='none'
}

function mostrar3 (){
    document.getElementById('info').style.display='none'
    document.getElementById('sol1').style.display='none'
    document.getElementById('mercurio2').style.display='none'
    document.getElementById('venus3').style.display='block'
    document.getElementById('tierra4').style.display='none'
    document.getElementById('marte5').style.display='none'
    document.getElementById('jupiter6').style.display='none'
    document.getElementById('saturno7').style.display='none'
    document.getElementById('urano8').style.display='none'
    document.getElementById('neptuno9').style.display='none'
document.getElementById('info2').style.display='none'
document.getElementById('info3').style.display='block'
document.getElementById('info4').style.display='none'
document.getElementById('info5').style.display='none'
document.getElementById('info6').style.display='none'
document.getElementById('info7').style.display='none'
document.getElementById('info8').style.display='none'
document.getElementById('info9').style.display='none'
}

function mostrar4 (){
    document.getElementById('info').style.display='none'
    document.getElementById('sol1').style.display='none'
    document.getElementById('mercurio2').style.display='none'
    document.getElementById('venus3').style.display='none'
    document.getElementById('tierra4').style.display='block'
    document.getElementById('marte5').style.display='none'
    document.getElementById('jupiter6').style.display='none'
    document.getElementById('saturno7').style.display='none'
    document.getElementById('urano8').style.display='none'

    document.getElementById('neptuno9').style.display='none'
document.getElementById('info2').style.display='none'
document.getElementById('info3').style.display='none'
document.getElementById('info4').style.display='block'
document.getElementById('info5').style.display='none'
document.getElementById('info6').style.display='none'
document.getElementById('info7').style.display='none'
document.getElementById('info8').style.display='none'
document.getElementById('info9').style.display='none'
}

function mostrar5 (){
    document.getElementById('info').style.display='none'
    document.getElementById('sol1').style.display='none'
    document.getElementById('mercurio2').style.display='none'
    document.getElementById('venus3').style.display='none'
    document.getElementById('tierra4').style.display='none'
    document.getElementById('marte5').style.display='block'
    document.getElementById('jupiter6').style.display='none'
    document.getElementById('saturno7').style.display='none'
    document.getElementById('urano8').style.display='none'
    document.getElementById('neptuno9').style.display='none'
document.getElementById('info2').style.display='none'
document.getElementById('info3').style.display='none'
document.getElementById('info4').style.display='none'
document.getElementById('info5').style.display='block'
document.getElementById('info6').style.display='none'
document.getElementById('info7').style.display='none'
document.getElementById('info8').style.display='none'
document.getElementById('info9').style.display='none'
}

function mostrar6 (){
    document.getElementById('info').style.display='none'
    document.getElementById('sol1').style.display='none'
    document.getElementById('mercurio2').style.display='none'
    document.getElementById('venus3').style.display='none'
    document.getElementById('tierra4').style.display='none'
    document.getElementById('marte5').style.display='none'
    document.getElementById('jupiter6').style.display='block'
    document.getElementById('saturno7').style.display='none'
    document.getElementById('urano8').style.display='none'
    document.getElementById('neptuno9').style.display='none'
document.getElementById('info2').style.display='none'
document.getElementById('info3').style.display='none'
document.getElementById('info4').style.display='none'
document.getElementById('info5').style.display='none'
document.getElementById('info6').style.display='block'
document.getElementById('info7').style.display='none'
document.getElementById('info8').style.display='none'
document.getElementById('info9').style.display='none'
}

function mostrar7 (){
    document.getElementById('info').style.display='none'
    document.getElementById('sol1').style.display='none'
    document.getElementById('mercurio2').style.display='none'
    document.getElementById('venus3').style.display='none'
    document.getElementById('tierra4').style.display='none'
    document.getElementById('marte5').style.display='none'
    document.getElementById('jupiter6').style.display='none'
    document.getElementById('saturno7').style.display='block'
    document.getElementById('urano8').style.display='none'
    document.getElementById('neptuno9').style.display='none'
document.getElementById('info2').style.display='none'
document.getElementById('info3').style.display='none'
document.getElementById('info4').style.display='none'
document.getElementById('info5').style.display='none'
document.getElementById('info6').style.display='none'
document.getElementById('info7').style.display='block'
document.getElementById('info8').style.display='none'
document.getElementById('info9').style.display='none'
}

function mostrar8 (){
    document.getElementById('info').style.display='none'
    document.getElementById('sol1').style.display='none'
    document.getElementById('mercurio2').style.display='none'
    document.getElementById('venus3').style.display='none'
    document.getElementById('tierra4').style.display='none'
    document.getElementById('marte5').style.display='none'
    document.getElementById('jupiter6').style.display='none'
    document.getElementById('saturno7').style.display='none'
    document.getElementById('urano8').style.display='block'
    document.getElementById('neptuno9').style.display='none'
document.getElementById('info2').style.display='none'
document.getElementById('info3').style.display='none'
document.getElementById('info4').style.display='none'
document.getElementById('info5').style.display='none'
document.getElementById('info6').style.display='none'
document.getElementById('info7').style.display='none'
document.getElementById('info8').style.display='block'
document.getElementById('info9').style.display='none'
}

function mostrar9 (){
    document.getElementById('info').style.display='none'
    document.getElementById('sol1').style.display='none'
    document.getElementById('mercurio2').style.display='none'
    document.getElementById('venus3').style.display='none'
    document.getElementById('tierra4').style.display='none'
    document.getElementById('marte5').style.display='none'
    document.getElementById('jupiter6').style.display='none'
    document.getElementById('saturno7').style.display='none'
    document.getElementById('urano8').style.display='none'
    document.getElementById('neptuno9').style.display='block'
document.getElementById('info2').style.display='none'
document.getElementById('info3').style.display='none'
document.getElementById('info4').style.display='none'
document.getElementById('info5').style.display='none'
document.getElementById('info6').style.display='none'
document.getElementById('info7').style.display='none'
document.getElementById('info8').style.display='none'
document.getElementById('info9').style.display='block'
}






